# Generated by Django 5.1.4 on 2024-12-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True)),
                ('source', models.CharField(default='', max_length=50)),
                ('political_affiliation', models.CharField(default='', max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
