# Generated by Django 5.1.4 on 2024-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='political_affiliation',
            field=models.CharField(choices=[('Dem', 'Democrat'), ('Reb', 'Republican'), ('', '')], default='', max_length=3),
        ),
    ]
