# Generated by Django 5.1.4 on 2025-01-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_political_affiliation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
