# Generated by Django 5.1.4 on 2025-01-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shownToUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='political_affiliation',
            field=models.CharField(choices=[(1, 'Democrat'), (2, 'Republican'), (3, 'Democrat'), (4, 'Republican'), (5, 'Republican'), ('', '')], default='', max_length=3),
        ),
    ]
