# Generated by Django 5.1.4 on 2025-01-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_showntouser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='a_title',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='political_affiliation',
            field=models.CharField(choices=[(1, 'Pro-Democrat'), (2, 'Pro-Republican'), (3, 'Anti-Democrat'), (4, 'Anti-Republican'), (5, 'Neutral'), ('', '')], default='', max_length=3),
        ),
    ]
