# Generated by Django 5.1.4 on 2025-01-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_a_title_article_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='political_affiliation',
            field=models.CharField(choices=[(1, 'Democrat'), (2, 'Republican'), (3, 'Neutral')], default=0, max_length=3),
        ),
    ]
