# Generated by Django 5.1.4 on 2025-01-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
